### PR TITLE
Allow style object to be passed down, and ref to reference the actual element

### LINKED ISSUE #8: Cannot pass styles to web component
Hi. Thanks for this package. It seems like I cannot pass style props like an object to the custom element after converting to a React component.

### PR DESCRIPTION
**Pull request by leifriksheim**
Fixes #8 

Also uses a [forwardRef](https://reactjs.org/docs/forwarding-refs.html) to make refs point to the actual custom element and not the React wrapper.

### CODE REVIEW

**Comment by leifriksheim** [comment]
The ref change might be a breaking change, unfortunately. IMO it makes more sense to reference the actual element rather than the React wrapper. At the moment you need to access the element like this `ref.current?.ref.current`.

**Comment by BBKolton** [comment]
Hi @leifriksheim, thank you for the PR! Could you walk me through why you changed the ref to reference the element directly? My understanding of most use cases for this wrapper is that people will use it inside of a React context, and so I assume that it would be best for developers to be able to reference the React component wrapper when necessary. 

Ultimately, I'm a bit unfamiliar with refs, but as I read the code, my understanding is that this change would make it impossible to reference the actual react element anymore, since the ref will always be pushed down to the custom element instead. In addition to being a breaking change, doesn't this preclude the ability from devs to ever target the react element with a ref?

**Comment by BBKolton** [comment]
Also: Thank you for the additional tests, and the style changes look great

**Comment by leifriksheim** [comment]
Hi @BBKolton. 

`forwardRef` is typically used with higher-order components so the wrapper component becomes essentially invisible when using it in your app. It's primarily for use with libraries so that they can provide a consistent way to access elements that have been wrapped in other components. You can read a bit more about it [here](https://reactjs.org/docs/forwarding-refs.html)

The reason I forwarded the ref, in this case, is that the React wrapper itself does not expose any methods the user can interact with (since it is just a wrapper component). On the contrary, a `custom-input` element might have a method like `focus()`. I suggest it would be more intuitive to access the DOM element directly so we can write something like this:

```jsx
import { CustomInput, CustomButton } from './web-components'

function TextInputWithFocusButton() {
  const inputEl = useRef(null);
  const onButtonClick = () => {
    // `current` points to the actual web component
    inputEl.current.focus();
  };
  return (
    <>
      <CustomInput ref={inputEl} type="text" />
      <CustomButton onClick={onButtonClick}>Focus the input</CustomButton>
    </>
  );
}
```

I'm not a React expert, so there could maybe be instances where the user wants to reference the React wrapper, but I cannot think of any use case myself. If you want you could just cherry-pick the style addition, and use more time to look at edge-cases. I would be happy to get the style addition merged so I do not have to keep a separate fork. Thanks for the package 👍

**Comment by BBKolton** [comment]
Hey @leifriksheim, I had a sanity check with a more experienced React developer on my team, and he agreed that the forwardRef change was a good idea. I'll be merging your changes and releasing a new update today!

**Comment by BBKolton** [comment]
Changes now available on v4.0.0. Thanks!

**Pull request merged**
